services:
    _defaults:
        autowire: true
        autoconfigure: true

    app.swagger.user.search_filter:
        class: App\Infrastructure\Documentation\SwaggerSearchFilter
        decorates: app.domain.user.search_filter
        arguments:
            $decorated: '@app.swagger.user.search_filter.inner'

    app.swagger.user_event.search_filter:
        class: App\Infrastructure\Documentation\SwaggerSearchFilter
        decorates: app.domain.user_event.search_filter
        arguments:
            $decorated: '@app.swagger.user_event.search_filter.inner'

    app.swagger.review.search_filter:
        class: App\Infrastructure\Documentation\SwaggerSearchFilter
        decorates: app.domain.review.search_filter
        arguments:
            $decorated: '@app.swagger.review.search_filter.inner'

    app.swagger.review.group_filter:
        class: App\Infrastructure\Documentation\SwaggerGroupFilter
        decorates: 'app.domain.review.group_filter'
        arguments:
            $decorated: '@app.swagger.review.group_filter.inner'

    app.swagger.review_event.search_filter:
        class: App\Infrastructure\Documentation\SwaggerSearchFilter
        decorates: app.domain.review_event.search_filter
        arguments:
            $decorated: '@app.swagger.review_event.search_filter.inner'

    app.swagger.review_comment.search_filter:
        class: App\Infrastructure\Documentation\SwaggerSearchFilter
        decorates: app.domain.review_comment.search_filter
        arguments:
            $decorated: '@app.swagger.review_comment.search_filter.inner'
