api_platform:
    title: Code Review System
    description: Engeenering project created to ephasize advantages of combining DDD, CQRS and Event Sourcing patterns along with near real time updates via Server-Sent Events.
    graphql:
        enabled: true
        graphiql:
            enabled: true
    mapping:
        paths:
            - '%kernel.project_dir%/src/Application/Document'
            - '%kernel.project_dir%/src/Domain/User'
            - '%kernel.project_dir%/src/Domain/Review'
            - '%kernel.project_dir%/config/packages/api_platform_resources'

    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        jsonapi:
            mime_types: ['application/vnd.api+json']
        xml:
            mime_types: ['application/xml', 'text/xml']
        html:
            mime_types: ['text/html']

    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
        jsonld:
            mime_types: ['application/ld+json']
        jsonapi:
            mime_types: ['application/vnd.api+json']

    path_segment_name_generator: api_platform.path_segment_name_generator.dash

    exception_to_status:
        Assert\InvalidArgumentException: 400

    # Enable Swagger UI authorization.
    swagger:
        api_keys:
            - { name: 'Authorization', type: 'header' }
            - { name: 'token', type: 'query' }
