framework:
    messenger:
        transports:
             commands: '%env(MESSENGER_TRANSPORT_DSN)%/commands'
             events: '%env(MESSENGER_TRANSPORT_DSN)%/events'

        routing:
             # Users
             'App\Application\Command\CreateUserCommand': commands
             'App\Application\Command\ChangeUserPasswordCommand': commands
             'App\Application\Command\ChangeUserEmailCommand': commands
             'App\Domain\User\Event\UserCreated': events
             'App\Domain\User\Event\UserPasswordChanged': events
             'App\Domain\User\Event\UserEmailChanged': events
             # Reviews
             'App\Application\Command\CreateReviewCommand': commands
             'App\Application\Command\StartReviewCheckCommand': commands
             'App\Application\Command\ChangeReviewCommitCommand': commands
             'App\Domain\Review\Event\ReviewCreated': events
             'App\Domain\Review\Event\ReviewNeedsCheck': events
             'App\Domain\Review\Event\ReviewCheckFinished': events
             'App\Domain\Review\Event\ReviewAutomatedChecksStatusChanged': events

        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - validation
            messenger.bus.queries:
                middleware:
                    - validation
            messenger.bus.events:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
