api_platform:
    resource: .
    type: api_platform
    prefix: /api

homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /api/docs
