App\Domain\Review\Review:
  attributes:
    id:
      groups:
        - ReviewRead
    gitRepositoryUrl:
      groups:
        - ReviewRead
    currentCommitHash:
      groups:
        - ReviewRead
    automatedChecks:
      groups:
        - ReviewRead
    status:
      groups:
        - ReviewRead
    automatedChecksStatus:
      groups:
        - ReviewRead
    owner:
      groups:
        - ReviewRead
    comments:
      groups:
        - ReviewRead
