App\Domain\User\User:
  attributes:
    id:
      groups:
        - UserRead
        - UserReadLess
    email:
      groups:
        - UserRead
        - UserReadLess
    roles:
      groups:
        - UserRead
