App\Domain\Review\Review:
  shortName: Review
  attributes:
    normalization_context:
      groups: ['ReviewRead']
    denormalization_context:
      groups: ['ReviewWrite']
  collectionOperations:
    get:
      method: GET
      access_control: "is_granted('ROLE_ADMIN')"
      filters:
        - app.domain.review.search_filter
        - app.domain.review.group_filter
  itemOperations:
    get:
      method: GET
      access_control: "is_granted('ROLE_ADMIN') or (user and object.isGranted(user))"
      filters:
        - app.domain.review.group_filter

App\Domain\Review\ReviewEventStore:
  shortName: ReviewEvent
  attributes:
    normalization_context:
      groups: ['ReviewEventRead']
    denormalization_context:
      groups: ['ReviewEventWrite']
  collectionOperations:
    get:
      method: GET
      access_control: "is_granted('ROLE_ADMIN')"
      filters:
          - app.domain.review_event.search_filter
          - app.domain.review_event.order_filter
  itemOperations:
    get:
      method: GET
      access_control: "is_granted('ROLE_ADMIN') or (user and object.isGranted(user))"

App\Application\Document\ReviewDocument:
  shortName: Review
  attributes:
    iri: api_reviews_get_item
    normalization_context:
      groups: ['ReviewRead']
    denormalization_context:
      groups: ['ReviewWrite']
  collectionOperations:
    post:
      method: POST
      controller: App\Application\Action\CreateReviewAction
      access_control: "is_granted('ROLE_USER')"
  itemOperations: []

App\Application\Document\ReviewChangeCommitDocument:
  shortName: Review
  attributes:
    iri: api_reviews_get_item
    normalization_context:
      groups: ['ReviewChangeCommitRead']
    denormalization_context:
      groups: ['ReviewChangeCommitWrite']
  collectionOperations: []
  itemOperations:
    change_commit:
      method: POST
      path: '/reviews/{id}/change-commit'
      controller: App\Application\Action\ChangeReviewCommitAction

App\Application\Document\ReviewAddCommentDocument:
  shortName: Review
  attributes:
    iri: api_reviews_get_item
    normalization_context:
      groups: ['ReviewAddCommentRead']
    denormalization_context:
      groups: ['ReviewAddCommentWrite']
  collectionOperations: []
  itemOperations:
    change_commit:
      method: POST
      path: '/reviews/{id}/comments/add'
      controller: App\Application\Action\AddReviewCommentAction
