App\Application\Document\UserDocument:
  shortName: User
  attributes:
    normalization_context:
      groups: ['UserRead']
    denormalization_context:
      groups: ['UserWrite']
  collectionOperations:
    post:
      method: POST
      controller: App\Application\Action\CreateUserAction
      access_control: "is_granted('ROLE_ADMIN')"
  itemOperations:
    get:
      method: GET
      controller: App\Application\Action\GetUserAction
      access_control: "is_granted('ROLE_ADMIN') or (user and object.isGranted(user))"
