parameters:
    env(REDIS_URI): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
#            $commandBus: '@messenger.bus.commands'
#            $queryBus: '@messenger.bus.queries'
#            $eventBus: '@messenger.bus.events'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Domain,Migrations,Tests,Kernel.php}'

    App\Application\Action\:
        resource: '../src/Application/Action'
        tags: ['controller.service_arguments']

    App\Domain\User\UserRepositoryInterface:
        class: App\Infrastructure\ORM\Repository\UserRepository

    app.redis.session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@app.redis.client'

    app.redis.client:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URI)%'
