parameters:
    env(REDIS_URI): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Application\Action\:
        resource: '../src/Application/Action'
        tags: ['controller.service_arguments']

    app.redis.session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@app.redis.client'

    app.redis.client:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URI)%'
