apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercure
  labels:
    app: mercure
    environment: development
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mercure
      environment: development
      type: backend
  template:
    metadata:
      labels:
        app: mercure
        environment: development
        type: backend
    spec:
      containers:
        - name: api
          image: dunglas/mercure
          imagePullPolicy: Always
          env:
            - name: DEMO
              value: "1"
            - name: ADDR
              value: ":3333"
            - name: ALLOW_ANONYMOUS
              value: "1"
            - name: JWT_KEY
              value: "!UnsecureChangeMe!"
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: PUBLISH_ALLOWED_ORIGINS
              value: "http://localhost:30333,http://localhost:3333,http://mercure:3333,http://localhost:8080,http://review-system,http://localhost:30080"
          ports:
            - name: http
              containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 384Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: mercure
  labels:
    app: mercure
    environment: development
    type: backend
spec:
  type: NodePort
  ports:
    - port: 3333
      protocol: TCP
      targetPort: http
      nodePort: 30333
  selector:
    app: mercure
    environment: development
    type: backend
