apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    environment: development
    type: message-broker
spec:
  selector:
    matchLabels:
      app: rabbitmq
      environment: development
      type: message-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        environment: development
        type: message-broker
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7-management-alpine
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          resources:
            limits:
              cpu: 100m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 256Mi
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    environment: development
    type: message-broker
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
    environment: development
    type: message-broker
  ports:
    - protocol: TCP
      port: 5672
      targetPort: amqp
