POST http://localhost/api/reviews
Authorization: Bearer {{auth_token}}
Accept: application/json
Content-Type: application/json

{
    "gitRepositoryUrl": "https://github.com/k911/swoole-bundle.git",
    "currentCommitHash": "9713e619c13799f6a6ae552b23f4afed4e90b910"
}

###

POST http://localhost/api/reviews
Authorization: Bearer {{auth_token}}
Accept: application/json
Content-Type: application/json

{
    "gitRepositoryUrl": "https://github.com/knit-pk/api-v1-php.git",
    "currentCommitHash": "dsa"
}

###

POST http://localhost/api/reviews
Authorization: Bearer {{auth_token}}
Accept: application/json
Content-Type: application/json

{
    "gitRepositoryUrl": "https://github.com/knit-pk/api-v1-php.git",
    "currentCommitHash": "db91bad05129c140dff2dc153281bcbf8b69cf34"
}

###

GET http://localhost/api/reviews
Authorization: Bearer {{auth_token}}
Accept: application/json
Content-Type: application/json

###
