POST http://localhost:9501/api/users
Authorization: Bearer {{auth_token}}
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.pl",
    "plainPassword": "test@test",
    "roles": [
        "ROLE_USER",
        "ROLE_TEST"
    ]
}

> {% client.global.set("user_id", response.body.id); %}

###

GET http://localhost:9501/api/users/{{user_id}}
Authorization: Bearer {{auth_token}}
Accept: application/ld+json

###
