POST http://localhost:9501/api/users
Authorization: Bearer {{auth_token}}
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.pl",
    "roles": [
        "ROLE_USER",
        "ROLE_TEST"
    ]
}

> {% client.global.set("user_id", response.body.id); %}

###

GET http://localhost:9501/api/users/c6f905eb-22a5-4a84-a926-cd6079f7844b
Authorization: Bearer {{auth_token}}
Accept: application/ld+json

###

GET http://localhost:9501/api/users/{{my_user_id}}
Authorization: Bearer {{auth_token}}
Accept: application/ld+json
